openapi: 3.0.0
info:
  title: Project API
  description: API documentation for managing projects
  version: 1.0.0

servers:
  - url: http://localhost:5000/api

paths:
  /projects:
    post:
      summary: Create a new project with images
      operationId: createProject
      tags:
        - Project
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: "My Project"
                description:
                  type: string
                  example: "This is a description of the project."
                image:
                  type: array
                  items:
                    type: string
                    format: binary
                  description: Upload one or more images
                techStack:
                  type: string
                  example: "React,Node.js,MongoDB"
      responses:
        '201':
          description: Project created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

  /projects/{id}:
    get:
      summary: Get a project by ID
      operationId: getProjectById
      tags:
        - Project
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Project fetched successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
        '404':
          description: Project not found
        '500':
          description: Internal Server Error

components:
  schemas:
    Project:
      type: object
      properties:
        _id:
          type: string
        title:
          type: string
        description:
          type: string
        image:
          type: array
          items:
            type: string
        techStack:
          type: array
          items:
            type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
